/* Copyright (C) 2016 Index Exchange All Rights Reserved.
The information contained within this document is confidential, copyrighted and or trade secret. No part of this document may be reproduced or distributed in any form or by any means, in whole or in part, without the prior written permission of Index Exchange.
*/

var indexRootNamespaceRename=indexRootNamespaceRename||"indexapi";if(typeof indexRootNamespaceRename!=='string'){indexRootNamespaceRename="indexapi";}
(function(){'use strict';window[indexRootNamespaceRename]=window[indexRootNamespaceRename]||{};function indexMap(array,callback,thisArg){if(Array.prototype.map){return array.map(callback);}
if(typeof callback!=='function'){throw new TypeError(callback+' is not a function');}
var _this=thisArg;var mappedArray=new Array(array.length);for(var i=0;i<array.length;i++){if(i in array){mappedArray[i]=callback.call(_this,array[i],i,array);}}
return mappedArray;}
function indexTime(){if(Date.now){return Date.now();}
return new Date().getTime();}
function videoSupport(){var version=0;var isIE=(navigator.appVersion.indexOf("MSIE")!=-1)?true:false;var isWin=(navigator.appVersion.toLowerCase().indexOf("win")!=-1)?true:false;var isOpera=(navigator.userAgent.indexOf("Opera")!=-1)?true:false;if(navigator.plugins&&navigator.plugins.length){if(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]){var swVer=navigator.plugins["Shockwave Flash 2.0"]?" 2.0":"";var desc=navigator.plugins["Shockwave Flash"+swVer].description;var ary=desc.split(" ");version=ary[2].split(".")[0];}}else if(isIE&&isWin&&!isOpera){var tmp;try{tmp=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");version=tmp.getVariable("$version").split(" ")[1].split(",")[0];}catch(e){}
if(!version){try{tmp=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");tmp.AllowScriptAccess="always";version=tmp.getVariable("$version").split(" ")[1].split(",")[0];}catch(e){}}
if(!version)
{try{tmp=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");version=tmp.getVariable("$version").split(" ")[1].split(",")[0];}catch(e){}}}
return(version>=9||!!document.createElement('video').canPlayType);}
var indexapi=(function(){var _version='8.5';var _maxRequestLength=8000;var _maxDFPRequestLength=7500;var jwplayerScript;var Log=(function(){var LEVEL_OFF=0;var LEVEL_DEBUG=1;var level=LEVEL_OFF;var debug=function(message){if(level==LEVEL_DEBUG){console.log("[ASL] "+message);}};var enabled=function(enabled){level=enabled?LEVEL_DEBUG:LEVEL_OFF;};return{enabled:enabled,debug:debug};})();if(typeof document.documentMode!=='undefined'&&typeof document.documentMode<9){Log.enabled(true);Log.debug("ERROR: ASL v"+_version+" does not support IE versions running below 9 standards mode.");return;}
var serialize=function(obj){var json='{"id":"'+obj.id+'","site":{"page":"'+quote(obj.site.page)+'"';if(typeof obj.site.ref==='string'){json+=',"ref":"'+quote(obj.site.ref)+'"';}
json+='},"imp":[';for(var i=0;i<obj.imp.length;i++){var impObj=obj.imp[i];var ext=[];json+='{"id":"'+impObj.id+'"';if(typeof impObj.banner!=='undefined'){var banner=impObj.banner;json+=', "banner":{"w":'+banner.w+',"h":'+banner.h+',"topframe":'+String(banner.topframe)+"}";}
if(typeof impObj.video!=='undefined'){var video=impObj.video;var videoExt=[];json+=', "video":{"mimes":["'+indexMap(video.mimes,quote).join('","')+'"]';json+=', "minduration":'+video.minduration+', "maxduration": '+video.maxduration;if(typeof video.protocols!=='undefined'){json+=',"protocols":['+video.protocols.join(',')+']';}
if(typeof video.w!=='undefined'){json+=',"w":'+video.w;}
if(typeof video.h!=='undefined'){json+=',"h":'+video.h;}
if(typeof video.linearity!=='undefined'){json+=',"linearity":'+video.linearity;}
if(typeof video.api!=='undefined'){json+=',"api":['+video.api.join(',')+']';}
if(typeof video.delivery!=='undefined'){json+=',"delivery":['+video.delivery.join(',')+']';}
if(typeof video.maxbitrate!=='undefined'){json+=',"maxbitrate":'+video.maxbitrate;}
if(typeof video.minbitrate!=='undefined'){json+=',"minbitrate":'+video.minbitrate;}
if(typeof video.playbackmethod!=='undefined'){json+=',"playbackmethod":['+video.playbackmethod.join(',')+']';}
if(typeof video.pos!=='undefined'){json+=',"pos":'+video.pos;}
if(typeof video.startdelay!=='undefined'){json+=',"startdelay":'+video.startdelay;}
if(typeof video.battr!=='undefined'){json+=',"battr":['+video.battr.join(',')+']';}
if(typeof video.ext!=='undefined'&&typeof video.ext.playertype==='string'){videoExt.push('"playertype":'+video.ext.playertype);}
if(videoExt.length>0){json+=',"ext":{'+videoExt.join()+'}';}
json+='}';}
if(typeof impObj.bidfloor==='number'){json+=',"bidfloor":'+impObj.bidfloor;if(typeof impObj.bidfloorcur==='string'){json+=',"bidfloorcur":"'+quote(impObj.bidfloorcur)+'"';}}
if(typeof impObj.ext.sid==='string'&&(!impObj.ext.sid.match(/^\s*$/))){ext.push('"sid":"'+quote(impObj.ext.sid)+'"');}
if(typeof impObj.ext.siteID==='number'){ext.push('"siteID":'+impObj.ext.siteID);}
if(ext.length>0){json+=',"ext":{'+ext.join()+'}';}
if(i+1==obj.imp.length){json+='}';}else{json+='},';}}
json+="]}";return json;};var escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;var meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'};function escapeCharacter(character){var escaped=meta[character];if(typeof escaped==='string'){return escaped;}else{return'\\u'+('0000'+character.charCodeAt(0).toString(16)).slice(-4);}}
function quote(string){escapable.lastIndex=0;if(escapable.test(string)){return string.replace(escapable,escapeCharacter);}else{return string;}}
function Bid(_impression,_videoImpression,_adm,_brandID,_brandName,_dealID,_dealName,_dspID,_internalDealID,_price,_priceLevel,_seatID,_VASTCreativeURL,_VASTErrorURL,_ttl){var _videoTargeting=[];var getAdm=function(){return _adm;};var getBrandID=function(){return _brandID;};var getBrandName=function(){return _brandName;};var getDealID=function(){return _dealID;};var getDealName=function(){return _dealName;};var getDSPID=function(){return _dspID;};var getImpression=function(){return _impression;};var getInternalDealID=function(){return _internalDealID;};var getPrice=function(){return _price;};var getPriceLevel=function(){return _priceLevel;};var getSeatID=function(){return _seatID;};var getVASTCreativeURL=function(){return _VASTCreativeURL;};var setVASTCreativeURL=function(VASTCreativeURL){if(typeof VASTCreativeURL!=='string'){Log.debug("ERROR: VAST creative URL is not a valid URL");return false;}
_VASTCreativeURL=VASTCreativeURL;return true;};var createTargetParams=function(prefix){if(typeof _VASTCreativeURL!=='string'||_VASTCreativeURL.length==0){Log.debug("ERROR: Can not generate target params for non-video bid");return'';}
if(typeof prefix!=='string'||prefix.length==0){Log.debug("ERROR: Can not generate target params without valid string prefix");return'';}
var queryList=[];queryList.push(getBidUrlTargets(prefix));queryList.push("IVT="+getTargetValue(prefix));var custParams=encodeURIComponent(queryList.join("&"));return custParams;};var getBidUrlTargets=function(prefix){var regex=/^https?:\/\/.*\/pcreative\?(.*)/i;var match=regex.exec(_VASTCreativeURL);if(match===null){Log.debug("ERROR: Can not generate target params for non-video bid");return'';}
if(_videoTargeting.length>0){return _videoTargeting.join('&');}
var paramList=match[1].split("&");param:for(var i=0;i<paramList.length;i++){var keyValue=paramList[i].split('=');if(!isCommonPcreativeParam(keyValue[0])){_videoTargeting.push(prefix+'_'+keyValue[0]+"="+keyValue[1]);}}
return _videoTargeting.join('&');};var getTargetValue=function(prefix){var pl=_dealID?_dealID:_priceLevel;return(prefix+"_pl_"+pl);};var getVASTErrorURL=function(){return _VASTErrorURL;};var getVideoImpression=function(){return _videoImpression;};var getTTL=function(){return _ttl;};return{createTargetParams:createTargetParams,getBidUrlTargets:getBidUrlTargets,getTargetValue:getTargetValue,getAdm:getAdm,getBrandID:getBrandID,getBrandName:getBrandName,getDealID:getDealID,getDealName:getDealName,getDSPID:getDSPID,getImpression:getImpression,getInternalDealID:getInternalDealID,getPrice:getPrice,getPriceLevel:getPriceLevel,getSeatID:getSeatID,getVASTCreativeURL:getVASTCreativeURL,getVASTErrorURL:getVASTErrorURL,getVideoImpression:getVideoImpression,getTTL:getTTL,setVASTCreativeURL:setVASTCreativeURL};}
function validateImpressionParams(slotID,siteID,bidFloor,bidFloorCurrency){var reject=false;if(typeof slotID!=='string'){Log.debug("ERROR: Slot ID is not a string.");reject=true;}
if(typeof bidFloor!=='undefined'&&(typeof bidFloor!=='number'||bidFloor<0)){Log.debug("ERROR: Bid Floor is not a valid number.");reject=true;}
if(typeof bidFloorCurrency!=='undefined'&&(typeof bidFloorCurrency!=='string'||bidFloorCurrency.length!==3)){Log.debug("ERROR: Bid Floor Currency is not a valid ISO currency string.");reject=true;}
if(typeof siteID!=='undefined'&&(typeof siteID!=='number'||siteID%1!==0||siteID<0)){Log.debug("ERROR: Site ID is not a valid number.");reject=true;}
if(reject){return false;}
return true;}
function validateVideoParams(mimes,minduration,maxduration,minPlayTime,protocols,width,height,linearity){var reject=false;var i;if(typeof mimes==='undefined'||!(mimes instanceof Array)){Log.debug("ERROR: Mimes is not an array.");reject=true;}else{if(mimes.length<1){Log.debug("ERROR: Mimes is empty.");reject=true;}
for(i=0;i<mimes.length;i++){if(typeof mimes[i]!=='string'||mimes[i].length<1){Log.debug("ERROR: Mimes index "+i+" is not a valid string.");reject=true;}}}
if(typeof minduration!=='number'||minduration%1!==0||minduration<0){Log.debug("ERROR: Minimum Duration is not a valid number.");reject=true;}
if(typeof maxduration!=='number'||maxduration%1!==0||maxduration<0){Log.debug("ERROR: Maximum Duration is not a valid number.");reject=true;}
if(typeof minPlayTime!=='undefined'&&(typeof minPlayTime!=='number'||minPlayTime%1!==0||minPlayTime<0)){Log.debug("ERROR: Minimum Play Time is not a valid number.");reject=true;}
if(typeof protocols==='undefined'||!(protocols instanceof Array)){Log.debug("ERROR: Protocols is not an array.");reject=true;}else{if(protocols.length<1){Log.debug("ERROR: Protocols is empty.");reject=true;}
for(i=0;i<protocols.length;i++){if(typeof protocols[i]!=='number'||protocols[i]%1!==0||protocols[i]<1){Log.debug("ERROR: Protocols index "+i+" is not a valid number.");reject=true;}}}
if(typeof width!=='undefined'&&(typeof width!=='number'||width%1!==0||width<1)){Log.debug("ERROR: Width is not a valid number.");reject=true;}
if(typeof height!=='undefined'&&(typeof height!=='number'||height%1!==0||height<1)){Log.debug("ERROR: Height is not a valid number.");reject=true;}
if(typeof linearity!=='undefined'&&(typeof linearity!=='number'||linearity%1!==0||linearity<1)){Log.debug("ERROR: Linearity is not a valid number.");reject=true;}
if(reject){return false;}
return true;}
function Impression(_id,_request,_slotID,_width,_height,_bidFloor,_bidFloorCurrency,_siteID){_id=_id.toString();var _valid={slotID:true,width:true,height:true,bidFloor:true,bidFloorCurrency:true,siteID:true};var getImpressionID=function(){return _id;};var getSlotID=function(){return _slotID;};var getRequest=function(){return _request;};var isValid=function(){for(var key in _valid){if(!_valid[key]){return false;}}
return true;};var getObject=function(){if(!isValid()){return undefined;}
var retObj={id:_id,banner:{w:_width,h:_height},ext:{sid:_slotID}};if(typeof _bidFloor==='number'){retObj.bidfloor=_bidFloor;}
if(typeof _bidFloorCurrency==='string'){retObj.bidfloorcur=_bidFloorCurrency;}
if(typeof _siteID==='number'){retObj.ext.siteID=_siteID;}
return retObj;};var setBidFloor=function(bidFloorCurrency,bidFloorCPM){var reject=false;if(typeof bidFloorCPM!=='number'||bidFloorCPM<0){Log.debug("ERROR: Bid Floor for Request "+_id+" is not a valid number.");_valid.bidFloor=false;reject=true;}
if(typeof bidFloorCurrency!=='string'||bidFloorCurrency.length!==3){Log.debug("ERROR: Bid Floor Currency for Request "+_id+" is not a valid ISO currency string.");_valid.bidFloorCurrency=false;reject=true;}
if(reject){Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");return false;}
_bidFloorCurrency=bidFloorCurrency;_bidFloor=bidFloorCPM;_valid.bidFloor=true;_valid.bidFloorCurrency=true;return true;};return{getImpressionID:getImpressionID,getSlotID:getSlotID,getRequest:getRequest,setBidFloor:setBidFloor,getObject:getObject};}
function Response(_request,_bids,_status,_x3){var _videoTargeting=[];var getBids=function(){return _bids;};var getRequest=function(){return _request;};var getStatus=function(){return _status;};var getX3=function(){return _x3;};var createMasterVideoTag=function(masterVideoTag){var targetParams=[];var keyTargets=[];for(var i=0;i<_bids.length;i++){var bid=_bids[i];if(bid.getVASTCreativeURL()){targetParams.push(bid.getBidUrlTargets(bid.getVideoImpression().getSlotID()));keyTargets.push(bid.getTargetValue(bid.getVideoImpression().getSlotID()));var currentMasterTag=encodeURIComponent(masterVideoTag)+encodeURIComponent(targetParams.join('&')+'&IVT='+keyTargets.join(','));if(currentMasterTag.length>_maxDFPRequestLength){targetParams.pop();keyTargets.pop();break;}}}
targetParams.push(getRequestUrlTargets());var keyParams="IVT="+keyTargets.join(",");targetParams.push(keyParams);var custParams=encodeURIComponent(targetParams.join("&"));var vposParam=_getQueryParameterValue("vpos",masterVideoTag);if(typeof vposParam==='undefined'){var vpos=_request.getVideoPosition();if(typeof vpos!=='undefined'){masterVideoTag+="&vpos="+vpos;}}
var mridxParam=_getQueryParameterValue("mridx",masterVideoTag);if(typeof mridxParam==='undefined'){var mridx=_request.getMidrollIndex();if(typeof mridx!=='undefined'){masterVideoTag+="&mridx="+mridx;}}
var pposParam=_getQueryParameterValue("ppos",masterVideoTag);if(typeof pposParam==='undefined'){var ppos=_request.getPodPosition();if(typeof ppos!=='undefined'){masterVideoTag+="&ppos="+ppos;}}
return buildMasterVideoTag(masterVideoTag,custParams);};var getRequestUrlTargets=function(){var regex=/^https?:\/\/.*\/pcreative\?(.*)/i;if(_bids.length>0){var match=regex.exec(_bids[0].getVASTCreativeURL());}else{return'';}
if(match===null){Log.debug("ERROR: Can not generate target params for non-video bid");return'';}
if(_videoTargeting.length>0){return _videoTargeting.join('&');}
var paramList=match[1].split("&");param:for(var i=0;i<paramList.length;i++){var keyValue=paramList[i].split('=');if(isCommonPcreativeParam(keyValue[0])){_videoTargeting.push('pc_'+keyValue[0]+"="+keyValue[1]);}}
return _videoTargeting.join('&');};return{getBids:getBids,getRequest:getRequest,getStatus:getStatus,getX3:getX3,createMasterVideoTag:createMasterVideoTag,getRequestUrlTargets:getRequestUrlTargets};}
function isCommonPcreativeParam(key){return(key==='au'||key==='n'||key==='epr'||key==='u'||key==='pr'||key==='unk1')}
function Request(_id,_siteID){_id=_id.toString();var _currentImpressionID=0;var _requestSent=false;var _pageUrl;var _topframe;var _hostname=window.location.protocol==='https:'?'https://sandbox.ht.indexexchange.com':'http://origin.headertag.com';var _getX3=false;var _videoPosition;var _midrollIndex;var _podPosition;var _valid={hostname:true};if(top===self){_pageUrl='https://weather.com';_topframe=1;}else{_pageUrl=document.referrer;_topframe=0;}
var _timeout;_timedOut[_id]=false;_callbacks[_id]={};var _impressions=[];var _buildRequest=function(){var json={};json.id=_id;json.imp=[];json.site={page:_pageUrl};if(typeof document.referrer==='string'){json.site.ref=document.referrer;}
for(var i=0;i<_impressions.length;i++){var imp=_impressions[i].getObject();if(typeof imp==='undefined'){continue;}
if(imp.banner){imp.banner.topframe=_topframe;}
json.imp.push(imp);}
return json;};var isValid=function(){for(var key in _valid){if(!_valid[key]){return false;}}
return true;};var addImpression=function(slotID,width,height,bidFloor,bidFloorCurrency,siteID){var reject=false;if(!validateImpressionParams(slotID,siteID,bidFloor,bidFloorCurrency)){reject=true;}
if(typeof width!=='number'||width%1!==0||width<1){Log.debug("ERROR: Width for Request "+_id+" is not a valid number.");reject=true;}
if(typeof height!=='number'||height%1!==0||height<1){Log.debug("ERROR: Height for Request "+_id+" is not a valid number.");reject=true;}
if(reject){return undefined;}
var impression=Impression(_currentImpressionID,this,slotID,width,height,bidFloor,bidFloorCurrency,siteID);_currentImpressionID++;_impressions.push(impression);Log.debug("DEBUG: Impression successfully added.");return impression;};var addVideoImpression=function(slotID,mimes,minduration,maxduration,protocols,width,height,bidFloor,bidFloorCurrency,linearity,siteID){var reject=false;if(!validateImpressionParams(slotID,siteID,bidFloor,bidFloorCurrency)){reject=true;}
if(!validateVideoParams(mimes,minduration,maxduration,undefined,protocols,width,height,linearity)){reject=true;}
if(reject){return undefined;}
var videoImpression=VideoImpression(_currentImpressionID,this,slotID,mimes,minduration,maxduration,protocols,width,height,bidFloor,bidFloorCurrency,linearity,siteID);_currentImpressionID++;_impressions[videoImpression.getImpressionID()]=videoImpression;Log.debug("DEBUG: Video Impression successfully added.");return videoImpression;};var addOutstreamImpression=function(slotID,playerType,mimes,minduration,maxduration,minPlayTime,width,height,bidFloor,bidFloorCurrency,siteID){var reject=false;var protocols=[2,3,5,6];if(typeof playerType!=='number'||playerType%1!==0||playerType<1||playerType>9){Log.debug("ERROR: Invalid playertype for outstream video in Request "+_id+".");reject=true;}
if(!validateImpressionParams(slotID,siteID,bidFloor,bidFloorCurrency)){reject=true;}
if(!validateVideoParams(mimes,minduration,maxduration,minPlayTime,protocols,width,height)){reject=true;}
if(_tabletCheck()){Log.debug("ERROR: ASL v"+_version+" does not support tablets for outstream.");reject=true;}
if(reject){return undefined;}
var videoImpression=VideoImpression(_currentImpressionID,this,slotID,mimes,minduration,maxduration,protocols,width,height,bidFloor,bidFloorCurrency,1,siteID,playerType,minPlayTime);_currentImpressionID++;_impressions.push(videoImpression);Log.debug("DEBUG: Outstream Video Impression successfully added.");return videoImpression;};var addMasterVideoTagImpression=function(slotID,videoTag,slotDef,commonArgs,width,height,startDelay,maxduration){var minduration=_getQueryParameterValue("min_ad_duration",videoTag);minduration=typeof minduration==='undefined'?0:+minduration;maxduration=maxduration||_getQueryParameterValue("max_ad_duration",videoTag);maxduration=typeof maxduration==='undefined'?60:+maxduration;var protocols=commonArgs.protocols;var bidFloorCurrency=commonArgs.bidFloorCurrency;var mimes=slotDef.mimes||commonArgs.mimes;var siteID=slotDef.siteID;var bidFloor=slotDef.bidFloor||commonArgs.bidFloor;var skippable=slotDef.skippable||commonArgs.skippable;var minBitRate=slotDef.minBitRate||commonArgs.minBitRate;var maxBitRate=slotDef.maxBitRate||commonArgs.maxBitRate;var apiList=slotDef.apiList||commonArgs.apiList;var playbackMethods=slotDef.playbackMethods||commonArgs.playbackMethods;var deliveryMethods=slotDef.deliveryMethods||commonArgs.deliveryMethods;var linearity=_getQueryParameterValue("vad_type",videoTag);switch(linearity){case"linear":linearity=1;break;case"nonlinear":linearity=2;break;default:linearity=1;}
var reject=false;if(typeof bidFloor==='undefined'){bidFloorCurrency=undefined;}
if(!validateImpressionParams(slotID,siteID,bidFloor,bidFloorCurrency)){reject=true;}
if(!validateVideoParams(mimes,minduration,maxduration,undefined,protocols,width,height)){reject=true;}
if(reject){return undefined;}
var videoImpression=VideoImpression(_currentImpressionID,this,slotID,mimes,minduration,maxduration,protocols,width,height,bidFloor,bidFloorCurrency,linearity,siteID,undefined,undefined);if(typeof videoImpression!=='undefined'){if(typeof commonArgs.position!=='undefined'){videoImpression.setPosition(commonArgs.position);}
if(typeof startDelay!=='undefined'){videoImpression.setStartDelay(startDelay);}
if(typeof skippable!=='undefined'){videoImpression.setSkippable(skippable);}
if(typeof minBitRate!=='undefined'){videoImpression.setMinBitrate(minBitRate);}
if(typeof maxBitRate!=='undefined'){videoImpression.setMaxBitrate(maxBitRate);}
if(typeof apiList!=='undefined'){videoImpression.setAPI(apiList);}
if(typeof playbackMethods!=='undefined'){videoImpression.setPlaybackMethods(playbackMethods);}
if(typeof deliveryMethods!=='undefined'){videoImpression.setDeliveryMethods(deliveryMethods);}}
_currentImpressionID++;_impressions.push(videoImpression);Log.debug("DEBUG: Master Video Tag Impression successfully added.");return videoImpression;};var getID=function(){return _id;};var getImpressions=function(){return _impressions;};var getResponse=function(){return _responses[_id];};var getVideoPosition=function(){return _videoPosition;}
var getMidrollIndex=function(){return _midrollIndex;}
var getPodPosition=function(){return _podPosition;}
var _tabletCheck=function(){var check=false;(function(a){if((/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino|android|ipad|playbook|silk/i).test(a)||(/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i).test(a.substr(0,4))){check=true;}})(navigator.userAgent||navigator.vendor||window.opera);return check;};var _sendReq=function(async){if(_requestSent){Log.debug("ERROR: Request "+_id+" has already been sent, will not send request.");return false;}
if(!isValid()){Log.debug("ERROR: Request "+_id+" will not be sent, invalid hostname specified.");return false;}
if(typeof _callback!=='function'&&typeof _callbacks[_id].request!=='function'&&typeof _callbacks[_id].success!=='function'){Log.debug("ERROR: Request "+_id+" is missing a callback, will not send request.");return false;}
if(_impressions.length<1){Log.debug("ERROR: Request "+_id+" contains no impressions, will not send request.");return false;}
var _currentTimeout=_timeout||_globalTimeout;if(_currentTimeout>0){_timer[_id]=window.setTimeout(function(){try{_responses[_id]=Response(_requests[_id],undefined,3);_timedOut[_id]=true;Log.debug("DEBUG: Request "+_id+" timed out");if(typeof _callbacks[_id].timeout==='function'){_callbacks[_id].timeout(_requests[_id]);}else if(typeof _callbacks[_id].request==='function'){_callbacks[_id].request(_responses[_id]);}else if(typeof _callback==='function'){_callback(_responses[_id]);}}catch(e){Log.debug("ERROR: Error in calling timeout callback: "+e.toString());}},_currentTimeout);}
var json=_buildRequest();if(!_hostname.match(/^https?:\/\//i)){var scriptSrc=location.protocol+'//'+_hostname;}else{var scriptSrc=_hostname;}
var jsonpCallbackParam='&fn='+encodeURIComponent(indexRootNamespaceRename+".jsonpResponse");scriptSrc+='/cygnus?v='+_version+'&s='+_siteID+jsonpCallbackParam;if(_getX3){scriptSrc+='&x3=1';}
if(!(/^https?:\/\/as(?:-sec)?\.casalemedia\.com/i.test(scriptSrc))){scriptSrc+='&C=1';}
while((scriptSrc+'&r='+encodeURIComponent(serialize(json))).length>_maxRequestLength){json.imp.pop();}
var jsonURI=encodeURIComponent(serialize(json));scriptSrc+='&r='+jsonURI
var scriptTag=document.createElement("script");scriptTag.setAttribute("async",async);scriptTag.setAttribute("src",scriptSrc);scriptTag.setAttribute("type","text/javascript");var firstScript=document.getElementsByTagName('script')[0];if(firstScript.parentNode){firstScript.parentNode.insertBefore(scriptTag,firstScript);}
_requestSent=true;Log.debug("DEBUG: Request "+_id+" successfully sent to "+_hostname+".");return true;};var sendRequest=function(){Log.debug("DEBUG: Sending request "+_id);return _sendReq(false);};var sendRequestAsync=function(){Log.debug("DEBUG: Sending request "+_id+" asynchronously");return _sendReq(true);};var setCallback=function(callback){if(typeof callback!=='function'){Log.debug("ERROR: Request callback for Request "+_id+" is not a function.");return false;}
_callbacks[_id].request=callback;return true;};var setErrorCallback=function(callback){if(typeof callback!=='function'){Log.debug("ERROR: Error callback for Request "+_id+" is not a function.");return false;}
_callbacks[_id].error=callback;return true;};var setPassCallback=function(callback){if(typeof callback!=='function'){Log.debug("ERROR: Pass callback for Request "+_id+" is not a function.");return false;}
_callbacks[_id].pass=callback;return true;};var setPageOverride=function(pageURL){if(typeof pageURL!=='string'){Log.debug("ERROR: Page Override for Request "+_id+" is not a string.");return false;}
_pageUrl=pageURL;return true;};var setRequestTimeout=function(timeoutMilliseconds){if(typeof timeoutMilliseconds!=='number'||timeoutMilliseconds%1!==0||timeoutMilliseconds<0){Log.debug("ERROR: Timeout for Request "+_id+" is not a number.");return false;}
_timeout=timeoutMilliseconds;return true;};var setSuccessCallback=function(callback){if(typeof callback!=='function'){Log.debug("ERROR: Success callback for Request "+_id+" is not a function.");return false;}
_callbacks[_id].success=callback;return true;};var setTimeoutCallback=function(callback){if(typeof callback!=='function'){Log.debug("ERROR: Timeout callback for Request "+_id+" is not a function.");return false;}
_callbacks[_id].timeout=callback;return true;};var setHostname=function(hostname){if(typeof hostname!=='string'||!(/^(?:[a-z0-9][a-z0-9-]*\.)+casalemedia\.com$/i.test(hostname))){Log.debug("ERROR: Hostname is not valid, will not send to this hostname.");_valid.hostname=false;return false;}
_hostname=hostname;_valid.hostname=true;return true;};var setVideoPosition=function(videoPosition){if(typeof videoPosition!=='string'){Log.debug("ERROR: Video Position is not valid.");_valid.videoPosition=false;return false;}
_videoPosition=videoPosition;_valid.videoPosition=true;return true;}
var setMidrollIndex=function(midrollIndex){if(typeof midrollIndex!=='number'||midrollIndex<1){Log.debug("ERROR: Midroll Index is not valid.");_valid.midrollIndex=false;return false;}
_midrollIndex=midrollIndex;_valid.midrollIndex=true;return true;}
var setPodPosition=function(podPosition){if(typeof podPosition!=='number'||podPosition<1){Log.debug("ERROR: Pod Position is not valid.");_valid.podPosition=false;return false;}
_podPosition=podPosition;_valid.podPosition=true;return true;}
var requestX3=function(getX3){if(typeof getX3!=='boolean'){Log.debug("ERROR: Request X3 parameter is not valid.");return false;}
_getX3=getX3;return true;};return{addImpression:addImpression,addVideoImpression:addVideoImpression,addOutstreamImpression:addOutstreamImpression,addMasterVideoTagImpression:addMasterVideoTagImpression,getID:getID,getImpressions:getImpressions,getResponse:getResponse,getVideoPosition:getVideoPosition,getMidrollIndex:getMidrollIndex,getPodPosition:getPodPosition,sendRequest:sendRequest,sendRequestAsync:sendRequestAsync,setCallback:setCallback,setErrorCallback:setErrorCallback,setPassCallback:setPassCallback,setPageOverride:setPageOverride,setRequestTimeout:setRequestTimeout,setSuccessCallback:setSuccessCallback,setTimeoutCallback:setTimeoutCallback,setHostname:setHostname,setVideoPosition:setVideoPosition,setMidrollIndex:setMidrollIndex,setPodPosition:setPodPosition,requestX3:requestX3};}
function VideoImpression(_id,_request,_slotID,_mimes,_minduration,_maxduration,_protocols,_width,_height,_bidFloor,_bidFloorCurrency,_linearity,_siteID,_playerType,_minPlayTime){_id=_id.toString();var _valid={slotID:true,mimes:true,minduration:true,maxduration:true,protocols:true,width:true,height:true,bidFloor:true,bidFloorCurrency:true,linearity:true,siteID:true,playerType:true,minPlayTime:true,apiList:true,deliveryMethods:true,maxBitrate:true,minBitrate:true,playbackMethods:true,position:true,startDelay:true};var _apiList;var _deliveryMethods;var _maxBitrate;var _minBitrate;var _playbackMethods;var _position;var _startDelay;var _battr=[16];var getImpressionID=function(){return _id;};var getRequest=function(){return _request;};var getSlotID=function(){return _slotID;};var isValid=function(){for(var key in _valid){if(!_valid[key]){return false;}}
return true;};var getObject=function(){if(!isValid()){return undefined;}
var retObj={id:_id,video:{mimes:_mimes,minduration:_minduration,maxduration:_maxduration,protocols:_protocols},ext:{sid:_slotID}};if(typeof _minPlayTime==='number'&&_minPlayTime>0){retObj.video.battr=_battr;}
if(typeof _startDelay==='number'){retObj.video.startdelay=_startDelay;}
if(typeof _minBitrate==='number'){retObj.video.minbitrate=_minBitrate;}
if(typeof _maxBitrate==='number'){retObj.video.maxbitrate=_maxBitrate;}
if(typeof _playbackMethods==='object'){retObj.video.playbackmethod=_playbackMethods;}
if(typeof _deliveryMethods==='object'){retObj.video.delivery=_deliveryMethods;}
if(typeof _apiList==='object'){retObj.video.api=_apiList;}
if(typeof _position==='number'){retObj.video.pos=_position;}
if(typeof _width==='number'){retObj.video.w=_width;}
if(typeof _height==='number'){retObj.video.h=_height;}
if(typeof _linearity==='number'){retObj.video.linearity=_linearity;}
if(typeof _playerType==='number'){retObj.video.ext={};retObj.video.ext.playertype=_playerType.toString();}
if(typeof _bidFloor==='number'){retObj.bidfloor=_bidFloor;}
if(typeof _bidFloorCurrency==='string'){retObj.bidfloorcur=_bidFloorCurrency;}
if(typeof _siteID==='number'){retObj.ext.siteID=_siteID;}
return retObj;};var setAPI=function(apiList){var reject=false;if(typeof apiList==='undefined'||!(apiList instanceof Array)){Log.debug("ERROR: API list for Video Impression "+_id+" is not an array.");reject=true;}else{if(apiList.length<1){Log.debug("ERROR: API List for Video Impression "+_id+" is empty.");reject=true;}
for(var i=0;i<apiList.length;i++){if(typeof apiList[i]!=='number'||apiList[i]%1!==0||apiList[i]<1){Log.debug("ERROR: API list index "+i+" for Video Impression "+_id+" is not a valid number.");reject=true;}}}
if(reject){Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");_valid.apiList=false;return false;}
_apiList=apiList;_valid.apiList=true;return true;};var setBidFloor=function(bidFloorCurrency,bidFloorCPM){var reject=false;if(typeof bidFloorCPM!=='number'||bidFloorCPM<0){Log.debug("ERROR: Bid Floor for Request "+_id+" is not a valid number.");_valid.bidFloor=false;reject=true;}
if(typeof bidFloorCurrency!=='string'||bidFloorCurrency.length!==3){Log.debug("ERROR: Bid Floor Currency for Request "+_id+" is not a valid ISO currency string.");_valid.bidFloorCurrency=false;reject=true;}
if(reject){Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");return false;}
_bidFloorCurrency=bidFloorCurrency;_bidFloor=bidFloorCPM;_valid.bidFloor=true;_valid.bidFloorCurrency=true;return true;};var setDeliveryMethods=function(deliveryMethods){var reject=false;if(typeof deliveryMethods==='undefined'||!(deliveryMethods instanceof Array)){Log.debug("ERROR: Delivery Methods for Video Impression "+_id+" is not an array.");reject=true;}else{if(deliveryMethods.length<1){Log.debug("ERROR: Delivery Methods for Video Impression "+_id+" is empty.");reject=true;}
for(var i=0;i<deliveryMethods.length;i++){if(typeof deliveryMethods[i]!=='number'||deliveryMethods[i]%1!==0||deliveryMethods[i]<1){Log.debug("ERROR: Delivery Method index "+i+" for Video Impression "+_id+" is not a valid number.");reject=true;}}}
if(reject){Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");_valid.deliveryMethods=false;return false;}
_deliveryMethods=deliveryMethods;_valid.deliveryMethods=true;return true;};var setLinearity=function(linearity){if(typeof linearity!=='number'||linearity%1!==0||linearity<1){Log.debug("ERROR: Linearity for Video Impression "+_id+" is not a valid number.");Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");_valid.linearity=false;return false;}
_linearity=linearity;_valid.linearity=true;return true;};var setMaxBitrate=function(maxBitrate){if(typeof maxBitrate!=='number'||maxBitrate%1!==0||maxBitrate<1){Log.debug("ERROR: Max Bit Rate for Video Impression "+_id+" is not a valid number.");Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");_valid.maxBitrate=false;return false;}
_maxBitrate=maxBitrate;_valid.maxBitrate=true;return true;};var setMinBitrate=function(minBitrate){if(typeof minBitrate!=='number'||minBitrate%1!==0||minBitrate<0){Log.debug("ERROR: Min Bit Rate for Video Impression "+_id+" is not a valid number.");Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");_valid.minBitrate=false;return false;}
_minBitrate=minBitrate;_valid.minBitrate=true;return true;};var setPlaybackMethods=function(playbackMethods){var reject=false;if(typeof playbackMethods==='undefined'||!(playbackMethods instanceof Array)){Log.debug("ERROR: Playback Methods for Video Impression "+_id+" is not an array.");reject=true;}else{if(playbackMethods.length<1){Log.debug("ERROR: Playback Methods for Video Impression "+_id+" is empty.");reject=true;}
for(var i=0;i<playbackMethods.length;i++){if(typeof playbackMethods[i]!=='number'||playbackMethods[i]%1!==0||playbackMethods[i]<1){Log.debug("ERROR: Playback Method index "+i+" for Video Impression "+_id+" is not a valid number.");reject=true;}}}
if(reject){Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");_valid.playbackMethods=false;return false;}
_playbackMethods=playbackMethods;_valid.playbackMethods=true;return true;};var setPosition=function(pos){if(typeof pos!=='number'||pos%1!==0||pos<1){Log.debug("ERROR: Position for Video Impression "+_id+" is not a valid number.");Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");_valid.position=false;return false;}
_position=pos;_valid.position=true;return true;};var setProtocols=function(protocols){var reject=false;if(typeof protocols==='undefined'||!(protocols instanceof Array)){Log.debug("ERROR: Protocols for Video Impression "+_id+" is not an array.");reject=true;}else{if(protocols.length<1){Log.debug("ERROR: Protocols for Video Impression "+_id+" is empty.");reject=true;}
for(var i=0;i<protocols.length;i++){if(typeof protocols[i]!=='number'||protocols[i]%1!==0||protocols[i]<1){Log.debug("ERROR: Protocols index "+i+" for Video Impression "+_id+" is not a valid number.");reject=true;}}}
if(reject){Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");_valid.protocols=false;return false;}
_protocols=protocols;_valid.protocols=true;return true;};var setSkippable=function(minPlayTime){if(typeof minPlayTime!=='number'||minPlayTime%1!==0||minPlayTime<0){Log.debug("ERROR: Skip Time for Video Impression "+_id+" is not a valid number.");Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");_valid.minPlayTime=false;return false;}
_minPlayTime=minPlayTime;_valid.minPlayTime=true;return true;};var setStartDelay=function(startDelay){if(typeof startDelay!=='number'||startDelay%1!==0){Log.debug("ERROR: Start Delay for Video Impression "+_id+" is not a valid number.");Log.debug("DEBUG: Impression "+_id+" will not be added to the Request.");_valid.startDelay=false;return false;}
_startDelay=startDelay;_valid.startDelay=true;return true;};var getPlayerType=function(){return _playerType;};var getMinPlayTime=function(){return _minPlayTime;};return{getImpressionID:getImpressionID,getSlotID:getSlotID,getRequest:getRequest,setAPI:setAPI,setBidFloor:setBidFloor,setDeliveryMethods:setDeliveryMethods,setLinearity:setLinearity,setMaxBitrate:setMaxBitrate,setMinBitrate:setMinBitrate,setPlaybackMethods:setPlaybackMethods,setPosition:setPosition,setProtocols:setProtocols,setSkippable:setSkippable,setStartDelay:setStartDelay,getPlayerType:getPlayerType,getMinPlayTime:getMinPlayTime,getObject:getObject};}
function OutstreamImpressionController(_siteID,_slotID,_playerType,_positionList,_minduration,_maxduration,_minPlayTime,_width,_height,_bidFloor,_bidFloorCurrency){var _request=createRequest(_siteID);var _imp;var _impID;var _pageOverride;var _positionController=OutstreamPositionController(_slotID,_width,_height,_positionList);var _frequencyCap;var _cookieName;var _cookieValue;var _timeSent;var getPositionController=function(){return _positionController;};var setPageOverride=function(pageURL){if(_request.setPageOverride(pageURL)){_pageOverride=pageURL;return true;}
return false;};var _setCookie=function(cookieValue){if(typeof _cookieName==='string'){var date=new Date();date.setDate(date.getDate()+365);document.cookie=_cookieName+"="+cookieValue+"; expires="+date.toGMTString()+";path=/";}};var activate=function(){if(typeof _cookieName==='string'&&_cookieName.length>0&&new RegExp(_cookieName).test(document.cookie)){var cookies=document.cookie.split('; ');for(var i=0;i<cookies.length;i++){if(new RegExp(_cookieName).test(cookies[i])){var cookieValue=cookies[i].split('=')[1];if(typeof cookieValue!=='string'){cookieValue=0;_setCookie(cookieValue);break;}
for(var j=0;j<cookieValue.length;j++){if(cookieValue[i]<'0'||cookieValue[i]>'9'){cookieValue=0;_setCookie(cookieValue);break;}}
if(cookieValue>indexTime()){cookieValue=0;_setCookie(cookieValue);break;}
_cookieValue=parseInt(cookieValue,10);break;}}}else{cookieValue=0;_setCookie(cookieValue);}
if(typeof _frequencyCap!=='undefined'&&typeof _cookieValue!=='undefined'){if(indexTime()<=_cookieValue+(_frequencyCap*60000)){Log.debug("DEBUG: Frequency Cap in effect, stopping activation.");return false;}}
var mimes=['video/mp4'];if(!videoSupport()){Log.debug("ERROR: Browser does not support Flash 9 or HTML5 Video");return false;}
var _showResponse=function(outstreamObj){var position=_positionController.getActivePosition();var response=_request.getResponse();if(typeof response!=='undefined'&&response.getStatus()===0){var bids=response.getBids();var bid;for(var i=0;i<bids.length;i++){var imp=bids[i].getImpression()||bids[i].getVideoImpression();if(imp.getImpressionID()===_impID){bid=bids[i];break;}}
if(typeof bid==='undefined'){Log.debug("ERROR: Could not find impression id in response that matched impression id in request.");return;}
if(typeof bid.getTTL()!=='undefined'&&indexTime()<=_timeSent+(bid.getTTL()*1000)){_positionController.showVideo(position,bid);_setCookie(indexTime());}else{Log.debug("DEBUG: The TTL on the response has expired, will perform new JIT request.");var request=createRequest(_siteID);if(_pageOverride){request.setPageOverride(_pageOverride);}
var impression=request.addOutstreamImpression(_slotID,_playerType,mimes,_minduration,_maxduration,_minPlayTime,_width,_height,_bidFloor,_bidFloorCurrency,_siteID);var impID=impression.getImpressionID();request.setSuccessCallback(function(response){var bids=response.getBids();var bid;for(var i=0;i<bids.length;i++){var imp=bids[i].getImpression()||bids[i].getVideoImpression();if(imp.getImpressionID()===impID){bid=bids[i];break;}}
if(typeof bid!=='undefined'){_positionController.showVideo(position,bid);_setCookie(indexTime());}else{Log.debug("ERROR: JIT request failed to get a valid bid response.");}});request.setCallback(function(){Log.debug("ERROR: JIT request failed to get a successful response.");});request.sendRequestAsync();_request=request;}}else if(typeof response!=='undefined'&&response.getStatus()===1){Log.debug("DEBUG: Request has a passing response object.");}else{Log.debug("ERROR: Request does not have a valid response object. Position may have been activated before the Response was returned.");}};_positionController.setPositionCallback(function(){if(_request.getResponse()){_showResponse();}});_request.setSuccessCallback(function(){if(_positionController.getActivePosition()){_showResponse();}});_positionController.setReadyCallback(function(){var div1=document.createElement('div');var div2=document.createElement('div');div2.id='index-test-player_'+Math.floor(Math.random()*100000);div1.id='index-test-player_'+Math.floor(Math.random()*100000);div1.style.position='fixed';div1.style.top='0px';div1.style.left='0px';div1.style.width='1px';div1.style.height='1px';div1.appendChild(div2);document.body.appendChild(div1);jwplayer(div2.id).setup({file:window.location.protocol==='https:'?'https://js-sec.indexww.com/blank.mp4':'http://js.indexww.com/blank.mp4',width:1,height:1});var renderingMode;jwplayer(div2.id).onReady(function(){renderingMode=jwplayer(div2.id).getRenderingMode();if(renderingMode!=='flash'){jwplayer(div2.id).remove();window.setTimeout(function(){document.body.removeChild(document.getElementById(div1.id));},500);}else{window.setTimeout(function(){document.body.removeChild(document.getElementById(div1.id));},500);}
renderingMode==='flash'?mimes.push('video/flv','video/x-flv'):undefined;renderingMode==='html5'?mimes.push('video/webm'):undefined;_imp=_request.addOutstreamImpression(_slotID,_playerType,mimes,_minduration,_maxduration,_minPlayTime,_width,_height,_bidFloor,_bidFloorCurrency,_siteID);_impID=_imp.getImpressionID();_timeSent=indexTime();_request.sendRequestAsync();});jwplayer(div2.id).onError(function(){Log.debug("ERROR: Browser failed to setup up player, browser may not support jwplayer.");});_positionController.activate();});Log.debug("DEBUG: Outstream Impression Controller activated.");return true;};var setFrequencyCap=function(cookieName,frequencyCapInMinutes){var reject=false;if(typeof cookieName!=='string'||!(/^[\x21-\x2B\x2D-\x39\x3B-\x3C\x3E-\x7E]+$/.test(cookieName))){Log.debug("ERROR: Frequency Cap Cookie name is not a valid string.");reject=true;}
if(typeof frequencyCapInMinutes!=='number'||frequencyCapInMinutes%1!==0||frequencyCapInMinutes<1){Log.debug("ERROR: Frequency Cap Time is not a valid number.");reject=true;}
if(reject){return false;}
_cookieName=cookieName;_frequencyCap=frequencyCapInMinutes;Log.debug("DEBUG: Frequency Cap set to "+_frequencyCap+" minutes.");return true;};return{getPositionController:getPositionController,activate:activate,setFrequencyCap:setFrequencyCap,setPageOverride:setPageOverride};}
function OutstreamPositionController(_slotID,_maxWidth,_maxHeight,_positionList){var _activePosition;var _elementList={};var _positionCallback;var _impressionCallback;var _impressionCalled=false;var _readyCallback;var _readyCalled=false;var _dwellTime=2000;var _minPageTime=0;var _pageTime=0;var _volume=100;var _started=false;var _playing=false;var _onReadyComplete=false;var _pageVisible=true;var _player;if(typeof jwplayer==='undefined'){if(typeof jwplayerScript==='undefined'){var player='WeEJTrrG';var scriptSrc=window.location.protocol==='https:'?'https://content.jwplatform.com':'http://content.jwplatform.com';scriptSrc+='/libraries/'+player+'.js';jwplayerScript=document.createElement('script');jwplayerScript.setAttribute('async',true);jwplayerScript.setAttribute('src',scriptSrc);jwplayerScript.setAttribute('type','text/javascript');var firstScript=document.getElementsByTagName('script')[0];if(firstScript.parentNode){firstScript.parentNode.insertBefore(jwplayerScript,firstScript);}}
if(jwplayerScript.addEventListener){jwplayerScript.addEventListener('load',function(){if(typeof _readyCallback==='function'){_readyCalled=true;_readyCallback();}});}else{jwplayerScript.attachEvent('onreadystatechange',function(){if(typeof _readyCallback==='function'&&jwplayerScript.readyState==='loaded'){_readyCalled=true;_readyCallback();}});}}else if(typeof jwplayer==='function'){if(typeof _readyCallback==='function'){_readyCalled=true;_readyCallback();}}
function IndexIsOnScreen(id,width,height,percent){try{var elem=document.getElementById(id);var docElem=document.documentElement;if(elem===undefined||typeof elem.getBoundingClientRect===undefined){return undefined;}
var framebox={top:0,left:0};if(top!=self){framebox=elem.ownerDocument.defaultView.frameElement.getBoundingClientRect();}
var adbox=elem.getBoundingClientRect();if(adbox===undefined){return undefined;}
adbox={left:adbox.left+framebox.left,top:adbox.top+framebox.top,width:width,height:height};var standardsCompliant=top.pageXOffset!==undefined;var css1Compatible=((document.compatMode||"")==="CSS1Compat");var scrollX=standardsCompliant?top.pageXOffset:css1Compatible?top.document.documentElement.scrollLeft:top.document.body.scrollLeft;var scrollY=standardsCompliant?top.pageYOffset:css1Compatible?top.document.documentElement.scrollTop:top.document.body.scrollTop;if(scrollX===undefined||scrollY===undefined){return undefined;}
var vw=top.innerWidth||document.documentElement.clientWidth||document.body.clientWidth;var vh=top.innerHeight||document.documentElement.clientHeight||document.body.clientHeight;if(vh===undefined||vw===undefined){return undefined;}
var viewbox={left:scrollX,top:scrollY,width:vw,height:vh};var onscreen=(adbox.left>=0&&adbox.top+(adbox.height*(percent/100))>=0&&adbox.left+adbox.width<=viewbox.width&&adbox.top+adbox.height<=viewbox.height+(adbox.height*(percent/100)));return onscreen;}catch(e){return undefined;}}
var getActivePosition=function(){return _activePosition;};var setPositionCallback=function(callback){if(typeof callback!=='function'){Log.debug("ERROR: Position Callback was not a function.");return false;}
_positionCallback=callback;return true;};var setImpressionCallback=function(callback){if(typeof callback!=='function'){Log.debug("ERROR: Impression Callback was not a function.");return false;}
_impressionCallback=callback;return true;};var setMinDwellTime=function(dwellMilliseconds){if(typeof dwellMilliseconds!=='number'||dwellMilliseconds%1!==0||dwellMilliseconds<1){Log.debug("ERROR: Dwell Time was not a valid number.");return false;}
_dwellTime=dwellMilliseconds;return true;};var setDefaultVolume=function(volumePercent){if(typeof volumePercent!=='number'||volumePercent%1!==0||volumePercent<0||volumePercent>100){Log.debug("ERROR: Default Volume was not a valid number.");return false;}
_volume=volumePercent;return true;};var setMinPageTime=function(minMilliseconds){if(typeof minMilliseconds!=='number'||minMilliseconds%1!==0||minMilliseconds<1){Log.debug("ERROR: Min Page Time was not a valid number.");return false;}
_minPageTime=minMilliseconds;return true;};var showVideo=function(blockElement,bid){if(!document.body.contains(blockElement)){Log.debug("ERROR: Cannot show video in element that is not in the document.");return;}
Log.debug("DEBUG: Showing Video to position: "+blockElement.id);var playerDiv=document.createElement('div');playerDiv.id='index-player-div_'+Math.floor(Math.random()*100000);blockElement.insertBefore(playerDiv,blockElement.firstChild);_player=jwplayer(playerDiv.id).setup({file:window.location.protocol==='https:'?'https://js-sec.indexww.com/blank.mp4':'http://js.indexww.com/blank.mp4',controls:bid.getVideoImpression().getMinPlayTime()?true:false,width:_maxWidth,height:1,skin:'vapor',autostart:false,advertising:{client:'vast',skipoffset:bid.getVideoImpression().getMinPlayTime()}});_player.onReady(function(){if(_player.getRenderingMode()==='flash'){_player.container.parentNode.style.webkitTransition='height 0.2s ease, opacity 0.25s ease';_player.container.parentNode.style.mozTransition='height 0.2s ease, opacity 0.25s ease';_player.container.parentNode.style.transition='height 0.2s ease, opacity 0.25s ease';}
_player.container.style.webkitTransition='height 0.2s ease, opacity 0.25s ease';_player.container.style.mozTransition='height 0.2s ease, opacity 0.25s ease';_player.container.style.transition='height 0.2s ease, opacity 0.25s ease';_player.container.style.backgroundColor='black';_player.container.cursor='pointer';var mouseenter;var mouseleave;if(typeof _player.container.onmouseenter!=='undefined'){mouseenter='mouseenter';mouseleave='mouseleave';}else{mouseenter='mouseover';mouseleave='mouseout';}
if(_player.container.addEventListener){_player.container.addEventListener(mouseenter,function(){_player.setMute(false);});_player.container.addEventListener(mouseleave,function(){_player.setMute(true);});}else{_player.container.attachEvent('on'+mouseenter,function(){_player.setMute(false);});_player.container.attachEvent('on'+mouseleave,function(){_player.setMute(true);});}
_player.setVolume(_volume);_player.setMute();Log.debug("DEBUG: JWPlayer finished initialization.");window.setTimeout(function(){if(IndexIsOnScreen(blockElement.id,_maxWidth,_maxHeight,50)&&_pageVisible){_player.play();}
_onReadyComplete=true;},0);});_player.onBeforePlay(function(){if(_started){return;}
_started=true;_player.playAd(bid.getVASTCreativeURL());});_player.onAdImpression(function(){Log.debug("DEBUG: Ad Started Playing.");_player.resize(_maxWidth,_maxHeight);_playing=true;if(!IndexIsOnScreen(_activePosition.id,_maxWidth,_maxHeight,50)||!_pageVisible){if(_playing){_player.play();_playing=false;}}});var removePlayerDiv=function(){if(typeof _player!=='undefined'){_player.remove();_player=undefined;}
var div=document.getElementById(playerDiv.id);div.parentNode.removeChild(div);};_player.onAdSkipped(function(obj){Log.debug("DEBUG: Ad skipped.");_player.resize(_maxWidth,0);window.setTimeout(function(){removePlayerDiv();},1000);});_player.onAdTime(function(obj){if(typeof _impressionCallback==='function'&&obj.position>2&&!_impressionCalled){Log.debug("DEBUG: Ad reached 2 second mark");_impressionCallback(this);_impressionCalled=true;}});_player.onAdComplete(function(){_player.resize(_maxWidth,0);window.setTimeout(function(){Log.debug("DEBUG: Ad complete and player removed.");removePlayerDiv();},1000);});_player.onAdError(function(error){Log.debug("ERROR: JWPlayer Error "+error.code+": "+error.message);_player.resize(_maxWidth,0);window.setTimeout(function(){removePlayerDiv();},1000);});_player.onError(function(error){Log.debug("ERROR: JWPlayer Ad Error: "+error.message);_player.resize(_maxWidth,0);window.setTimeout(function(){removePlayerDiv();},1000);});return;};var setPositionBlocks=function(positionList){var reject=false;if(typeof positionList==='undefined'||!(positionList instanceof Array)){Log.debug("ERROR: Position List is not an array.");reject=true;}else{if(positionList.length<1){Log.debug("ERROR: Position List is empty.");reject=true;}
for(var i=0;i<positionList.length;i++){if(typeof positionList[i]!=='string'){Log.debug("ERROR: Position List index "+i+" is not a string.");reject=true;}}}
if(reject){return false;}
_positionList=positionList;return true;};var getSlotID=function(){return _slotID;};var activate=function(){var positionList=_positionList;if(positionList.length<1){Log.debug("ERROR: Failed activation of Position Controller, no positions in position list.");return false;}
if(_player){Log.debug("DEBUG: Position Controller already playing a video.");return false;}
var dwellTimes={};var previous=indexTime();_activePosition=undefined;for(var i=0;i<positionList.length;i++){var element=document.getElementById(positionList[i]);if(!element){Log.debug("DEBUG: "+positionList[i]+" cannot be found in the DOM, removed from position list.");positionList.splice(i,1);continue;}
_elementList[positionList[i]]=element;dwellTimes[positionList[i]]=0;}
var interval=window.setInterval(function(){var current=indexTime();var delta=current-previous;previous=current;if(_pageVisible){_pageTime+=delta;}
if(typeof positionList==='undefined'){return;}
if(positionList.length<1){Log.debug("DEBUG: No positions in the position list, cannot find active positions.");window.clearInterval(interval);return;}
for(var i=0;i<positionList.length;i++){var id=positionList[i];if(IndexIsOnScreen(id,_maxWidth,_maxHeight,0)&&_pageVisible){dwellTimes[id]+=delta;}else{dwellTimes[id]=0;}
if(dwellTimes[id]>=_dwellTime&&_pageTime>=_minPageTime&&typeof jwplayer!=='undefined'){if(typeof _activePosition==='undefined'&&typeof _positionCallback==='function'){Log.debug("DEBUG: Active position selected: "+id);window.clearInterval(interval);_activePosition=_elementList[id];_positionCallback(this);return;}}}},100);var scrollFunction=function(){if(typeof _player==='undefined'){return;}
if(_activePosition){if(_playing&&_onReadyComplete){if(!IndexIsOnScreen(_activePosition.id,_maxWidth,_maxHeight,50)){Log.debug("DEBUG: Player is at least 50% offscreen, pausing");_player.play();_playing=false;}}else if(_onReadyComplete){if(IndexIsOnScreen(_activePosition.id,_maxWidth,_maxHeight,50)){Log.debug("DEBUG: Player is at least 50% on screen, resuming");_player.play();_playing=true;}}}else{for(var id in _elementList){if(!IndexIsOnScreen(id,_maxWidth,_maxHeight,0)||!_pageVisible){dwellTimes[id]=0;}}}};if(window.addEventListener){window.addEventListener('scroll',scrollFunction);}else{window.attachEvent('onscroll',scrollFunction);}
var hidden;var handleVisibilityChange=function(event){var eventMap={focus:true,focusin:true,pageshow:true,blur:false,focusout:false,pagehide:false};event=event||window.event;if(event.type in eventMap){_pageVisible=eventMap[event.type];}else{_pageVisible=!document[hidden];}
if(typeof _player==='undefined'){return;}
if(_pageVisible){if(!_playing){_player.play();_playing=true;}}else{if(_playing){_player.play();_playing=false;}}};if(typeof document.hidden!=="undefined"){hidden="hidden";document.addEventListener("visibilitychange",handleVisibilityChange);}else if(typeof document.mozHidden!=="undefined"){hidden="mozHidden";document.addEventListener("mozvisibilitychange",handleVisibilityChange);}else if(typeof document.msHidden!=="undefined"){hidden="msHidden";document.addEventListener("msvisibilitychange",handleVisibilityChange);}else if(typeof document.webkitHidden!=="undefined"){hidden="webkitHidden";document.addEventListener("webkitvisibilitychange",handleVisibilityChange);}else if("onfocusin"in document){hidden=undefined;if(window.addEventListener){document.addEventListener("focusin",handleVisibilityChange);document.addEventListener("focusout",handleVisibilityChange);}else{document.attachEvent("onfocusin",handleVisibilityChange);document.attachEvent("onfocusout",handleVisibilityChange);}}else{hidden=undefined;if(window.addEventListener){window.addEventListener("pageshow",handleVisibilityChange);window.addEventListener("pagehide",handleVisibilityChange);window.addEventListener("focus",handleVisibilityChange);window.addEventListener("blur",handleVisibilityChange);}else{window.attachEvent("onpageshow",handleVisibilityChange);window.attachEvent("onpagehide",handleVisibilityChange);window.attachEvent("onfocus",handleVisibilityChange);window.attachEvent("onblur",handleVisibilityChange);}}
if(typeof document[hidden]!=='undefined'){handleVisibilityChange({type:document[hidden]?"blur":"focus"});}
Log.debug("DEBUG: Outstream Position Controller activated");return true;};var setReadyCallback=function(callback){if(typeof callback!=='function'){Log.debug("ERROR: JWPlayer Callback was not a function.");return false;}
_readyCallback=callback;if(typeof jwplayer==='function'&&!_readyCalled){_readyCallback();}
return true;};return{getActivePosition:getActivePosition,setPositionCallback:setPositionCallback,setImpressionCallback:setImpressionCallback,setReadyCallback:setReadyCallback,setMinDwellTime:setMinDwellTime,setDefaultVolume:setDefaultVolume,setMinPageTime:setMinPageTime,showVideo:showVideo,setPositionBlocks:setPositionBlocks,getSlotID:getSlotID,activate:activate};}
var _callback;var _globalTimeout=0;var _requests={};var _responses={};var _targetIDToBid={};var _callbacks={};var _timedOut={};var _timer={};var _requestCounter;var _midrollRequestCounter=0;var _pposCounter={};var deferQueue=window[indexRootNamespaceRename].deferQueue||[];var createRequest=function(siteID){if(typeof siteID!=='number'||siteID%1!==0||siteID<0){Log.debug("ERROR: Invalid siteID when creating Request");return undefined;}
if(typeof _requestCounter==='undefined'){_requestCounter=Math.floor(Math.random()*256);}else{_requestCounter=(_requestCounter+1)%256;}
var request=Request(String((new Date().getTime()%2592000)*256+_requestCounter+256),siteID);_requests[request.getID()]=request;return request;};var _permuteDurations=function(definedDurations,pmxd,pmad){var durations=[];definedDurations.sort();for(var j=0;j<definedDurations.length;j++){if(typeof definedDurations[j]!=='number'){continue;}
var iterations=Math.floor(pmxd/(definedDurations[j]*1000));if(typeof podMaxAds!=='undefined'){iterations=Math.min(iterations,podMaxAds);}
for(var k=0;k<iterations;k++){durations.push(definedDurations[j]*1000);}}
return durations;};var _getOptimizedDurations=function(videoOverrides,commonArgs,vpos,pmad,pmxd){var definedDurations=videoOverrides[vpos].durations||commonArgs.durations;if(!(definedDurations instanceof Array)||definedDurations.length===0){Log.debug("ERROR: No slot durations found for "+vpos+", used in an optimized pod.");return[];}
return _permuteDurations(definedDurations,pmxd,pmad);};var createRequestFromVastUrl=function(siteID,commonArgs,videoOverrides,vpos){var request=createRequest(siteID);var videoTag=commonArgs.masterVideoTag;if(typeof request==='undefined'){return undefined;}
if(typeof videoTag!=='string'){Log.debug("ERROR: Invalid videoTag when creating request from VAST URL");return undefined;}
if(typeof commonArgs!=='object'){Log.debug("ERROR: Invalid commonArgs when creating request from VAST URL");return undefined;}
if(typeof vpos!=='undefined'&&typeof vpos!=='string'){Log.debug("ERROR: Invalid position when creating request from VAST URL");return undefined;}
videoOverrides=videoOverrides||{};if(typeof videoOverrides!=='object'){Log.debug("ERROR: Invalid overrides when creating request from VAST URL");return undefined;}
var podMaxDuration=_getQueryParameterValue("pmxd",videoTag);var optimized=(typeof podMaxDuration!=='undefined');if(optimized){Log.debug("ERROR: ASL version "+_version+" does not support optimized pods");return;}
vpos=_getQueryParameterValue("vpos",videoTag)||vpos;var slotIDPrefix;var podTypes={preroll:0,midroll:0,postroll:0};var startDelay=0;switch(vpos){case"postroll":slotIDPrefix="po_1";podTypes[vpos]=1;startDelay=-2;request.setVideoPosition("postroll");break;case"midroll":var mridx=+_getQueryParameterValue("mridx",videoTag);slotIDPrefix="m_";if(optimized){mridx=++_midrollRequestCounter;}else if(typeof mridx==='undefined'||mridx<1){mridx=1;}
slotIDPrefix+=mridx;podTypes[vpos]=mridx;startDelay=-1;request.setVideoPosition("midroll");request.setMidrollIndex(mridx);break;case"preroll":default:slotIDPrefix="pr_1";podTypes[vpos]=1;startDelay=0;request.setVideoPosition("preroll");break;}
var podMaxAds=_getQueryParameterValue("pmad",videoTag);var durations=optimized?_getOptimizedDurations(videoOverrides,commonArgs,vpos,podMaxAds,podMaxDuration):[''];var dimensions=commonArgs.size?_getDimensions(commonArgs.size):_getDimensionsOfVideoTag(videoTag);if(typeof dimensions==='undefined'){return undefined;}
for(var j=0;j<durations.length;j++){var ppos;var slotID;if(!optimized){var pposParam=_getQueryParameterValue("ppos",videoTag);if(typeof pposParam!=='undefined'){ppos=+pposParam;_pposCounter[slotIDPrefix]=ppos;}else if(typeof _pposCounter[slotIDPrefix]!=='undefined'){ppos=++_pposCounter[slotIDPrefix];}else{ppos=1;_pposCounter[slotIDPrefix]=ppos;}
slotID=slotIDPrefix+"_"+ppos+"_s";request.setPodPosition(ppos);}else{ppos=j+1;slotID=slotIDPrefix+"_"+ppos;}
Log.debug("DEBUG: Building slot configuration for slot "+slotID);videoOverrides[vpos]=videoOverrides[vpos]||{};videoOverrides[vpos][podTypes[vpos]]=videoOverrides[vpos][podTypes[vpos]]||{};var slotDef=videoOverrides[vpos][podTypes[vpos]][ppos]||{};var duration=optimized?durations[j]:undefined;request.addMasterVideoTagImpression(slotID,videoTag,slotDef,commonArgs,dimensions.width,dimensions.height,startDelay,duration);}
return request;};var _getDimensionsOfVideoTag=function(videoTag){var dimensions=_getDimensions(_getQueryParameterValue("sz",videoTag));if(typeof dimensions==='undefined'){Log.debug("ERROR: Invalid dimensions in 'sz' field of master video tag: "+videoTag);return undefined;}
return dimensions;};var createRequestFromPlaylist=function(siteID,playlistXML,commonArgs,videoOverrides){var request=createRequest(siteID);if(typeof request==='undefined'){return undefined;}
if(typeof playlistXML!=='object'){Log.debug("ERROR: Invalid playlist XML when creating request from Playlist");return undefined;}
if(typeof commonArgs!=='object'){Log.debug("ERROR: Invalid commonArgs when creating request from Playlist");return undefined;}
videoOverrides=videoOverrides||{};if(typeof videoOverrides!=='object'){Log.debug("ERROR: Invalid overrides when creating request from Playlist");return undefined;}
var rootElementName=playlistXML.childNodes[0].localName;var adBreaks;switch(rootElementName){case"Playlist":adBreaks=playlistXML.getElementsByTagNameNS("*","Ad");break;case"VMAP":adBreaks=playlistXML.getElementsByTagNameNS("*","AdBreak");break;default:Log.debug("ERROR: Unrecognized playlist format retrieved from master video tag: "+commonArgs.masterVideoTag);return undefined;}
var slots={};var podTypes={preroll:0,midroll:0,postroll:0};for(var i=0;i<adBreaks.length;i++){var adBreak=adBreaks[i];var offset=(rootElementName==="Playlist")?_getStartDelay(adBreak.parentNode,rootElementName):_getStartDelay(adBreak,rootElementName);var videoTag=(rootElementName==="Playlist")?adBreak.textContent.trim():adBreak.getElementsByTagNameNS("*","AdTagURI")[0].textContent.trim();if(offset===undefined){Log.debug("ERROR: Could not parse start delay from ad pod element, skipping ad pod");continue;}
var slotIDPrefix;var vpos;switch(offset){case 0:vpos="preroll";if(!(offset in slots)){slots[offset]=true;podTypes[vpos]++;}
slotIDPrefix="pr_"+podTypes[vpos];break;case-2:vpos="postroll";if(!(offset in slots)){slots[offset]=true;podTypes[vpos]++;}
slotIDPrefix="po_"+podTypes[vpos];break;default:vpos="midroll";if(!(offset in slots)){slots[offset]=true;podTypes[vpos]++;}
var pod=_getQueryParameterValue("mridx",adBreak.textContent.trim());slotIDPrefix="m_";slotIDPrefix+=(typeof pod!=="undefined")?pod:podTypes[vpos];}
var podMaxDuration=_getQueryParameterValue("pmxd",videoTag);var optimized=(typeof podMaxDuration!=='undefined');if(optimized){Log.debug("ERROR: ASL version "+_version+" does not support optimized pods");continue;}
var podMaxAds=_getQueryParameterValue("pmad",videoTag);var durations=optimized?_getOptimizedDurations(videoOverrides,commonArgs,vpos,podMaxAds,podMaxDuration):[''];var dimensions=commonArgs.size?_getDimensions(commonArgs.size):_getDimensionsOfVideoTag(videoTag);if(typeof dimensions==='undefined'){return undefined;}
for(var j=0;j<durations.length;j++){var ppos=j+1;var slotID;if(!optimized){var pposParam=_getQueryParameterValue("ppos",videoTag);ppos=pposParam?pposParam:ppos;slotID=slotIDPrefix+"_"+ppos+"_s";}else{slotID=slotIDPrefix+"_"+ppos;}
Log.debug("DEBUG: Building slot configuration for slot "+slotID);videoOverrides[vpos]=videoOverrides[vpos]||{};videoOverrides[vpos][podTypes[vpos]]=videoOverrides[vpos][podTypes[vpos]]||{};var slotDef=videoOverrides[vpos][podTypes[vpos]][ppos]||{};var duration=optimized?durations[j]:undefined;request.addMasterVideoTagImpression(slotID,videoTag,slotDef,commonArgs,dimensions.width,dimensions.height,offset,duration);}}
return request;};var createOutstreamImpressionController=function(siteID,slotID,playerType,positionList,minduration,maxduration,minPlayTime,width,height,bidFloor,bidFloorCurrency){var reject=false;if(typeof siteID==='undefined'){Log.debug("ERROR: Site ID is not a valid number.");reject=true;}
if(typeof width==='undefined'){Log.debug("ERROR: Width is not a valid number.");reject=true;}
if(typeof height==='undefined'){Log.debug("ERROR: Height is not a valid number.");reject=true;}
if(typeof minPlayTime==='undefined'){Log.debug("ERROR: Minimum Play Time is not a valid number.");reject=true;}
if(!validateImpressionParams(slotID,siteID,bidFloor,bidFloorCurrency)){reject=true;}
if(typeof playerType!=='number'||playerType%1!==0||playerType<1||playerType>9){Log.debug("ERROR: Invalid playertype for outstream video in OutstreamImpressionController.");reject=true;}
if(typeof positionList==='undefined'||!(positionList instanceof Array)){Log.debug("ERROR: Position List is not an array.");reject=true;}else{if(positionList.length<1){Log.debug("ERROR: Position List is empty.");reject=true;}
for(var i=0;i<positionList.length;i++){if(typeof positionList[i]!=='string'){Log.debug("ERROR: Position List index "+i+" is not a string.");reject=true;}}}
if(!validateVideoParams(['video/mp4'],minduration,maxduration,minPlayTime,[2,3,5,6],width,height)){reject=true;}
if(reject){return undefined;}
var impressionController=OutstreamImpressionController(siteID,slotID,playerType,positionList,minduration,maxduration,minPlayTime,width,height,bidFloor,bidFloorCurrency);return impressionController;};var createOutstreamPositionController=function(slotID,maxWidth,maxHeight,positionList){var reject=false;if(typeof slotID!=='string'){Log.debug("ERROR: Slot ID for OutstreamPositionController is not a string.");reject=true;}
if(typeof positionList==='undefined'||!(positionList instanceof Array)){Log.debug("ERROR: Position List is not an array.");reject=true;}else{if(positionList.length<1){Log.debug("ERROR: Position List is empty.");reject=true;}
for(var i=0;i<positionList.length;i++){if(typeof positionList[i]!=='string'){Log.debug("ERROR: Position List index "+i+" is not a string.");reject=true;}}}
if(typeof maxWidth!=='number'||maxWidth%1!==0||maxWidth<1){Log.debug("ERROR: Width for OutstreamPositionController is not a valid number.");reject=true;}
if(typeof maxHeight!=='number'||maxHeight%1!==0||maxHeight<1){Log.debug("ERROR: Height for OutstreamPositionController is not a valid number.");reject=true;}
if(reject){return undefined;}
var positionController=OutstreamPositionController(slotID,maxWidth,maxHeight,positionList);return positionController;};var evalQueue=function(){if(!(deferQueue instanceof Array)){Log.debug("ERROR: deferQueue is not an Array, cannot evaluate.");return;}
for(var i=0;i<deferQueue.length;){if(typeof deferQueue[i]!=='function'){Log.debug("ERROR: deferQueue contains an element that is not a function, skipping.");deferQueue.splice(i,1);continue;}
try{deferQueue[i]();deferQueue.splice(i,1);}catch(e){Log.debug("ERROR: Error in deferQueue function: "+e.toString());deferQueue.splice(i,1);}}
return;};var jsonpResponse=function(JSONPObj){try{if(JSONPObj){if(typeof JSONPObj!=='object'||typeof JSONPObj.id==='undefined'){Log.debug("ERROR: Received an invalid JSON object in response.");return;}
var request=_requests[JSONPObj.id];Log.debug("DEBUG: Received JSON object in response for Request "+JSONPObj.id);if(typeof request==='undefined'){Log.debug("ERROR: Could not find Request with id: "+JSONPObj.id+".");return;}
var impressions=request.getImpressions();var bids=[];var x3;if(_timedOut[request.getID()]){return;}else{window.clearTimeout(_timer[request.getID()]);}
if(typeof JSONPObj.ext!=='undefined'){if(JSONPObj.ext.x3 instanceof Array){x3=JSONPObj.ext.x3;}}
if(typeof JSONPObj.seatbid==='undefined'){try{_responses[request.getID()]=Response(request,[],1,x3);Log.debug("DEBUG: Pass response parsed.");if(typeof _callbacks[request.getID()].pass==='function'){_callbacks[request.getID()].pass(request);}else if(typeof _callbacks[request.getID()].request==='function'){_callbacks[request.getID()].request(_responses[request.getID()]);}else if(typeof _callback==='function'){_callback(_responses[request.getID()]);}}catch(e){Log.debug("ERROR: Error in calling pass callback: "+e.toString());}
return;}
for(var i=0;i<JSONPObj.seatbid.length;i++){for(var j=0;j<JSONPObj.seatbid[i].bid.length;j++){var bid=JSONPObj.seatbid[i].bid[j];var impression;for(var k=0;k<impressions.length;k++){if(impressions[k].getImpressionID()===bid.impid){impression=impressions[k];break;}}
if(typeof impression==='undefined'){Log.debug("ERROR: Could not find Impression with id "+bid.impid+".");continue;}
if(typeof bid.ext!=='object'){Log.debug("ERROR: Bid extension of bid "+bid.impid+" is not an object.");continue;}
var vastURL=undefined;var errorURL=undefined;var videoimp=undefined;var imp=undefined;var adm=undefined;var brandID=undefined;var brandName=undefined;var internalDealID=undefined;var dealName=undefined;var dspID=undefined;var dealID=undefined;var price=undefined;var priceLevel=undefined;var seatID=undefined;var ttl=undefined;if(typeof bid.adm==='string'&&typeof bid.ext.vasturl=='undefined'&&typeof bid.ext.errorurl==='undefined'){adm=bid.adm;vastURL=undefined;errorURL=undefined;imp=impression;videoimp=undefined;}else if(typeof bid.adm!=='undefined'){Log.debug("ERROR: Bid contained no valid adm.");}
if(typeof bid.ext.advbrandid==='number'){brandID=bid.ext.advbrandid;}else if(typeof bid.ext.advbrandid!=='undefined'){Log.debug("ERROR: Bid contained no valid advertiser ID.");}
if(typeof bid.ext.advbrand==='string'){brandName=bid.ext.advbrand;}else if(typeof bid.ext.advbrand!=='undefined'){Log.debug("ERROR: Bid contained no valid advertiser brand name.");}
if(typeof bid.ext.deal==='number'){internalDealID=bid.ext.deal;}else if(typeof bid.ext.deal!=='undefined'){Log.debug("ERROR: Bid contained no valid internal deal ID.");}
if(typeof bid.ext.dealname==='string'){dealName=bid.ext.dealname;}else if(typeof bid.ext.dealname!=='undefined'){Log.debug("ERROR: Bid contained no valid deal name.");}
if(typeof bid.ext.dspid==='number'){dspID=bid.ext.dspid;}else if(typeof bid.ext.dspid!=='undefined'){Log.debug("ERROR: Bid contained no valid DSP ID.");}
if(typeof bid.dealid==='string'||typeof bid.ext.dealid==='string'){dealID=bid.dealid||bid.ext.dealid;}else if(typeof bid.dealid!=='undefined'){Log.debug("ERROR: Bid contained no valid deal ID.");}else if(typeof bid.ext.dealid!=='undefined'){Log.debug("ERROR: Bid contained no valid deal ID.");}
if(typeof bid.price==='number'){price=bid.price;}else if(typeof bid.price!=='undefined'){Log.debug("ERROR: Bid contained no valid price.");}
if(typeof bid.ext.pricelevel==='string'){priceLevel=bid.ext.pricelevel;}else if(typeof bid.ext.pricelevel!=='undefined'){Log.debug("ERROR: Price Level in the Bid was not a string.");continue;}
if(typeof JSONPObj.seatbid[i].seat==='string'){seatID=JSONPObj.seatbid[i].seat;}else if(typeof JSONPObj.seatbid[i].seat!=='undefined'){Log.debug("ERROR: Bid contained no valid seat.");}
if(typeof bid.ext.vasturl==='string'){vastURL=bid.ext.vasturl;videoimp=impression;imp=undefined;adm=undefined;}else if(typeof bid.ext.vasturl!=='undefined'){Log.debug("ERROR: Bid contained no valid VAST creative url.");}
if(typeof bid.ext.errorurl==='string'){errorURL=bid.ext.errorurl;}else if(typeof bid.ext.errorurl!=='undefined'){Log.debug("ERROR: Bid contained no valid VAST error url.");}
if(typeof bid.ext.ttl==='number'){ttl=bid.ext.ttl;}else if(typeof bid.ext.ttl!=='undefined'){Log.debug("ERROR: Bid contained invalid ttl value.");}
var bidObj=Bid(imp,videoimp,adm,brandID,brandName,dealID,dealName,dspID,internalDealID,price,priceLevel,seatID,vastURL,errorURL,ttl);bids.push(bidObj);}}}else{Log.debug("ERROR: Received an invalid JSON object in response.");return;}}catch(e){Log.debug("ERROR: Error parsing Response: "+e.toString());if(typeof request==='undefined'){Response(undefined,undefined,2,x3);return;}
try{_responses[request.getID()]=Response(request,undefined,2,x3);if(typeof _callbacks[request.getID()].error==='function'){_callbacks[request.getID()].error(request);}else if(typeof _callbacks[request.getID()].request==='function'){_callbacks[request.getID()].request(_responses[request.getID()]);}else if(typeof _callback==='function'){_callback(_responses[request.getID()]);}}catch(e){Log.debug("ERROR: Error in calling error callback: "+e.toString());}
return;}
if(typeof request!=='undefined'){if(bids.length>0){try{_responses[request.getID()]=Response(request,bids,0,x3);Log.debug("DEBUG: Successful response parsed.");if(typeof _callbacks[request.getID()].success==='function'){_callbacks[request.getID()].success(_responses[request.getID()]);}else if(typeof _callbacks[request.getID()].request==='function'){_callbacks[request.getID()].request(_responses[request.getID()]);}else if(typeof _callback==='function'){_callback(_responses[request.getID()]);}}catch(e){Log.debug("ERROR: Error in calling success callback: "+e.toString());}}else{try{_responses[request.getID()]=Response(request,bids,1,x3);Log.debug("DEBUG: Pass response parsed.");if(typeof _callbacks[request.getID()].pass==='function'){_callbacks[request.getID()].pass(request);}else if(typeof _callbacks[request.getID()].request==='function'){_callbacks[request.getID()].request(_responses[request.getID()]);}else if(typeof _callback==='function'){_callback(_responses[request.getID()]);}}catch(e){Log.debug("ERROR: Error in calling pass callback: "+e.toString());}}}
return;};var registerTargetMapping=function(targetID,bidObject){var reject=false;if(typeof targetID!=='string'){Log.debug("ERROR: Target ID in mapping is not a string.");reject=true;}
if(typeof bidObject!=='object'){Log.debug("ERROR: Bid in mapping is not an object.");reject=true;}
if(typeof bidObject!=='undefined'&&(typeof bidObject.getAdm!=='function'||typeof bidObject.getAdm()==='undefined')){Log.debug("ERROR: Bid object in mapping does not contain an adm.");reject=true;}
if(reject){return false;}
_targetIDToBid[targetID]=bidObject;return true;};var render=function(targetID){if(typeof targetID!=='string'){Log.debug("ERROR: Target ID to render is not a string.");return false;}
if(typeof _targetIDToBid[targetID]==='undefined'){Log.debug("ERROR: Could not find "+targetID+" in the bid mappings.");return false;}
var bid=_targetIDToBid[targetID];if(typeof bid.getImpression()==='undefined'){return false;}
var doc=document.getElementById(bid.getImpression().getSlotID());if(!doc){Log.debug("ERROR: Could not find div with id: "+bid.getImpression().getSlotID());return false;}
doc.innerHTML+=bid.getAdm();return true;};var setDebugMode=function(enabled){if(typeof enabled!=='boolean'){Log.debug("ERROR: Invalid debug mode parameter.");return;}
Log.enabled(enabled);return;};var setRequestCallback=function(callback){if(typeof callback!=='function'){Log.debug("ERROR: Request callback is not a function");return false;}
_callback=callback;return true;};var setRequestTimeout=function(timeoutMilliseconds){if(typeof timeoutMilliseconds!=='number'||timeoutMilliseconds%1!==0||timeoutMilliseconds<0){Log.debug("ERROR: Timeout is not a number.");return false;}
_globalTimeout=timeoutMilliseconds;return true;};var _parseTimeOffsetTime=function(attr){if(attr!==undefined){var a=attr.split(":");var seconds=(+a[0])*60*60+(+a[1])*60+(+a[2]);return seconds;}
return undefined;};var _getStartDelay=function(pod,rootElementName){switch(rootElementName){case"Playlist":switch(pod.localName){case"Preroll":return 0;case"Midroll":var attr=pod.getAttribute("timeOffset");if(attr.indexOf(":")>-1){return _parseTimeOffsetTime(attr);}
return-1;case"Postroll":return-2;}
case"VMAP":switch(pod.localName){case"AdBreak":var attr=pod.getAttribute("timeOffset");switch(attr){case"start":return 0;case"end":return-2;default:if(attr.indexOf(":")>-1){return _parseTimeOffsetTime(attr);}
return-1;}}}
return undefined;};var _getDimensions=function(dimensionsString){var sizes=dimensionsString.split(",");var dimensions={};var DEFAULT_DIMENSIONS={width:960,height:540}
if(sizes.length>0){var size=sizes[0].split("x");if(size.length!==2){Log.debug("ERROR: Received invalid size, must be of format WxH");dimensions=DEFAULT_DIMENSIONS;}else{dimensions.width=+size[0];dimensions.height=+size[1];}}
if(!_isValidDimensions(dimensions)){dimensions=DEFAULT_DIMENSIONS;}
return dimensions;};var _isValidDimensions=function(dimensions){if(typeof dimensions.width==='undefined'||typeof dimensions.height==='undefined'){return false;}
var validDimensions={1.78:true,1.67:true,1.6:true,1.33:true,1.25:true}
var minimumWidth=320;var minimumHeight=240;var supportedDimension=validDimensions[Math.round(dimensions.width/dimensions.height*100)/100]||false;var minimumSize=dimensions.width>=minimumWidth&&dimensions.height>=minimumHeight;return supportedDimension&&minimumSize;}
var _getQueryParameterValue=function(parameter,url){var regex=new RegExp("[?&]"+parameter+"(=([^&#]*)|&|#|$)","i");var results=regex.exec(url);if(!results||!results[2]){return undefined;}
return decodeURIComponent(results[2].replace(/\+/g," "));};function buildMasterVideoTag(masterVideoTag,custParamsString){if(typeof masterVideoTag!=='string'||masterVideoTag.length===0){Log.debug("ERROR: Master video tag is not a valid string.");return masterVideoTag;}
if(typeof custParamsString!=='string'){Log.debug("ERROR: cust_params is not a valid string.");return masterVideoTag;}
var re=/(^.+&cust_params=)(.+?)(&.+|$)/;var found=masterVideoTag.match(re);if(found){var custParams=found[2]+'%26'+custParamsString;masterVideoTag=found[1]+custParams+found[3];}else{masterVideoTag+='&cust_params='+custParamsString;}
return masterVideoTag;};return{createRequest:createRequest,createRequestFromPlaylist:createRequestFromPlaylist,createRequestFromVastUrl:createRequestFromVastUrl,createOutstreamImpressionController:createOutstreamImpressionController,createOutstreamPositionController:createOutstreamPositionController,evalQueue:evalQueue,jsonpResponse:jsonpResponse,registerTargetMapping:registerTargetMapping,render:render,setDebugMode:setDebugMode,setRequestCallback:setRequestCallback,setRequestTimeout:setRequestTimeout,buildMasterVideoTag:buildMasterVideoTag,deferQueue:deferQueue};})();window[indexRootNamespaceRename]=indexapi;window[indexRootNamespaceRename].evalQueue();})();
